export enum Configs {
    APIKEY_APICN = "APIKEY_APICN",
    APIKEY_GEONAMES = "APIKEY_GEONAMES",
    APIKEY_GOOGLE = "APIKEY_GOOGLE",
    APIKEY_IPINFO = "APIKEY_IPINFO",
    APIKEY_OPENWEATHER = "APIKEY_OPENWEATHER",
    FORCE_MOCK_APICN_API = "FORCE_MOCK_APICN_API",
    FORCE_MOCK_GEONAMES_API = "FORCE_MOCK_GEONAMES_API",
    FORCE_MOCK_GOOGLE_API = "FORCE_MOCK_GOOGLE_API",
    FORCE_MOCK_IPINFO_API = "FORCE_MOCK_IPINFO_API",
    FORCE_MOCK_OPENWEATHER_API = "FORCE_MOCK_OPENWEATHER_API",
    MOCK_INVALID_APIS = "MOCK_INVALID_APIS",
    USE_MOCK_ENDPOINTS = "USE_MOCK_ENDPOINTS"
}
